### data
train_dataset_type: erniekit
eval_dataset_type: erniekit
train_dataset_path: /root/paddlejob/share-storage/gpfs/system-public/liuhao63/Fleet_Former_cice/models/PaddleFleet/DSV4_Model_Accuracy/data/train.jsonl
train_dataset_prob: "1.0"
eval_dataset_path: /root/paddlejob/share-storage/gpfs/system-public/liuhao63/Fleet_Former_cice/models/PaddleFleet/DSV4_Model_Accuracy/data/train.jsonl
eval_dataset_prob: "1.0"
packing: false
truncate_packing: false
max_seq_len: 1024
mix_strategy: concat

dataset_type: map
random_shuffle: false
dataloader_shuffle: false
use_template: false

### model
model_name_or_path: /root/paddlejob/share-storage/gpfs/system-public/liuhao63/Fleet_Former_cice/models/PaddleFleet/DSV4_Model_Accuracy/fleet_checkpoint
_attn_implementation: eager
use_accuracy_compatible: true
use_dsv4_accuracy: true

### finetuning
stage: PT
fine_tuning: full
seed: 1234
do_train: true
do_eval: false
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
num_train_epochs: 1
max_steps: 10
eval_iters: 2000
eval_steps: 100000
evaluation_strategy: steps
save_steps: 20000
save_hf_steps: 20000
save_strategy: steps
logging_steps: 1
gradient_accumulation_steps: 2
logging_dir: ./logs/paddle/default/vdl
output_dir: ./logs/paddle/default/trainer
disable_tqdm: false
eval_accumulation_steps: 16

### parallel: single-node EP8, no PP/TP
tensor_model_parallel_size: 1
sequence_parallel: false
use_expert_parallel: true
expert_model_parallel_size: 8
pipeline_model_parallel_size: 1
num_hidden_layers: 4

### optimizer
weight_decay: 0.1
adam_beta2: 0.999
router_aux_loss_coef: 0.0
learning_rate: 1.0e-3
warmup_steps: 0
min_lr: 1.0e-4
decay_steps: 10
max_grad_norm: 0.0
lr_scheduler_type: cosine

### MoE
moe_token_dispatcher_type: deepep
moe_use_fusion_node: false
moe_router_load_balancing_type: none
moe_router_fusion: false
moe_deep_gemm: false
moe_router_force_load_balancing: false

### pp
pp_delay_scale_loss: true
overlap_p2p_comm: false
variable_seq_lengths: true
best_unbalanced_scheduler: false
pp_release_grads: true

### recompute
recompute_granularity: full
recompute_method: uniform
recompute_num_layers: 1

### amp
amp_master_grad: true
bf16: true
fp16_opt_level: O2

### checkpoint
save_checkpoint_format: flex_checkpoint
load_checkpoint_format: flex_checkpoint
save_safetensors: false
continue_training: true

### dataloader
dataloader_num_workers: 0

### misc
tensorwise_offload_optimizer: false
skip_profile_timer: false
load_via_cpu: false
fp32_residual_connection: false

### template
template_backend: custom
template: deepseek3

### DSv4-specific flags
multi_latent_attention: true
use_qk_norm: true
dsa_indexer_loss_coeff: 0.01
num_nextn_predict_layers: 1
num_empty_layers_add_in_tail: 1

# deterministic_mode: true
